// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOATiyTgFmGbyILEpoLYXITyJ9r0Clds',
    appId: '1:284034205458:web:639e672edf1016e9aed5cb',
    messagingSenderId: '284034205458',
    projectId: 'upscale-legal',
    authDomain: 'upscale-legal.firebaseapp.com',
    storageBucket: 'upscale-legal.appspot.com',
    measurementId: 'G-C8N40X6Q85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLxdIHNjjbNxmf9Q6jg1Q0ss93KaepfG8',
    appId: '1:284034205458:android:77e3e9eafb9d600faed5cb',
    messagingSenderId: '284034205458',
    projectId: 'upscale-legal',
    storageBucket: 'upscale-legal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmAeQ-bbnf4_fecNDilkHVF5c_LCao_jo',
    appId: '1:284034205458:ios:68f9ad325ba8b900aed5cb',
    messagingSenderId: '284034205458',
    projectId: 'upscale-legal',
    storageBucket: 'upscale-legal.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmAeQ-bbnf4_fecNDilkHVF5c_LCao_jo',
    appId: '1:284034205458:ios:1f03687312db15f2aed5cb',
    messagingSenderId: '284034205458',
    projectId: 'upscale-legal',
    storageBucket: 'upscale-legal.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
